[HDF5_jll]
libhdf5_path = "/leonardo/prod/spack/5.2/install/0.21/linux-rhel8-icelake/gcc-12.2.0/hdf5-1.14.3-flr43qytzge67qvbmjx4mszcm23s4d3b/lib/libhdf5.so"

[MPIPreferences]
__clear__ = ["preloads_env_switch"]
_format = "1.0"
abi = "OpenMPI"
binary = "system"
cclibs = []
libmpi = "/leonardo/prod/opt/libraries/openmpi/4.1.6/gcc--12.2.0/lib/libmpi"
mpiexec = "mpiexec"
preloads = []
